<?php
/*
 * Misc Options
 */
global $opt_name;
Redux::setSection( $opt_name, array(
    'title' => __( 'Misc', 'inspiry' ),
    'id'    => 'misc-section',
    'desc'  => __( 'This section contains options related to various features across the theme.', 'inspiry' ),
    'fields'=> array(

        array(
            'id'       => 'inspiry_google_reCAPTCHA',
            'type'     => 'switch',
            'title'    => __( 'Google reCAPTCHA', 'inspiry' ),
            'default'  => 0,
            'on'       => __( 'Enable', 'inspiry' ),
            'off'      => __( 'Disable', 'inspiry' ),
        ),
        array(
            'id'        => 'inspiry_reCAPTCHA_site_key',
            'type'      => 'text',
            'title'     => __( 'reCAPTCHA Site Key', 'inspiry' ),
            'required'  => array( 'inspiry_google_reCAPTCHA', '=', 1 ),
        ),
        array(
            'id'        => 'inspiry_reCAPTCHA_secret_key',
            'type'      => 'text',
            'title'     => __( 'reCAPTCHA Secret Key', 'inspiry' ),
            'required'  => array( 'inspiry_google_reCAPTCHA', '=', 1 ),
        ),
        array(
            'id'       => 'inspiry_reCAPTCHA_language',
            'type'     => 'select',
            'title'    => __( 'reCAPTCHA Language', 'inspiry' ),
            'options'  => array(
                "ar"    =>  "Arabic",
                "bn"    => "Bengali",
                "bg"    => "Bulgarian",
                "ca"    => "Catalan",
                "zh-CN" => "Chinese (Simplified)",
                "zh-TW" => "Chinese (Traditional)",
                "hr"    => "Croatian",
                "cs"    => "Czech" ,
                "da"    => "Danish",
                "nl"    => "Dutch",
                "en-GB" => "English (UK)",
                "en"    => "English (US)",
                "et"    => "Estonian",
                "fil"   => "Filipino",
                "fi"    => "Finnish",
                "fr"    => "French",
                "fr-CA" => "French (Canadian)",
                "de"    => "German",
                "gu"    => "Gujarati",
                "Value" => "Language",
                "de-AT" => "German (Austria)",
                "de-CH" => "German (Switzerland)",
                "el"    => "Greek",
                "iw"    => "Hebrew",
                "hi"    => "Hindi",
                "hu"    => "Hungarain",
                "id"    => "Indonesian",
                "it"    => "Italian",
                "ja"    => "Japanese",
                "kn"    => "Kannada",
                "ko"    => "Korean",
                "lv"    => "Latvian",
                "lt"    => "Lithuanian",
                "ms"    => "Malay",
                "ml"    => "Malayalam",
                "mr"    => "Marathi",
                "no"    => "Norwegian",
                "fa"    => "Persian",
                "pl"    => "Polish",
                "pt"    => "Portuguese",
                "pt-BR" => "Portuguese (Brazil)",
                "pt-PT" => "Portuguese (Portugal)",
                "ro"    => "Romanian",
                "ru"    => "Russian",
                "sr"    => "Serbian",
                "sk"    => "Slovak",
                "sl"    => "Slovenian",
                "es"    => "Spanish",
                "es-419" => "Spanish (Latin America)",
                "sv"    => "Swedish",
                "ta"    => "Tamil",
                "te"    => "Telugu",
                "th"    => "Thai",
                "tr"    => "Turkish",
                "uk"    => "Ukrainian",
                "ur"    => "Urdu",
                "vi"    => "Vietnamese"
            ),
            'default'  => 'en',
            'required'  => array( 'inspiry_google_reCAPTCHA', '=', 1 ),
        ),
        array(
            'id' => 'inspiry_agent_cc_email',
            'type' => 'text',
            'title' => __( 'CC Email Address for Messages to Agents', 'inspiry' ),
            'subtitle' => __( 'Given email address will receive a copy of every message sent to any agent.', 'inspiry' ),
            'desc' => __( 'You can provide multiple email addresses separated with comma.', 'inspiry' ),
        ),
        array(
            'id'        => 'inspiry_google_map_api_key',
            'type'      => 'text',
            'title'     => __( 'Google Map Api Key', 'inspiry' ),
            'subtitle' => __( 'Optional', 'inspiry' ),
        ),
        array(
            'id'       => 'inspiry_google_map_auto_lang',
            'type'     => 'switch',
            'title'    => __( 'Automatically Switch Google Map Language', 'inspiry' ),
            'subtitle'    => __( 'Based on site language from general settings OR current language if you are using WPML.', 'inspiry' ),
            'default'  => 0,
            'on'       => __( 'Enable', 'inspiry' ),
            'off'      => __( 'Disable', 'inspiry' ),
        ),

    ) ) );